/* Generated By:JavaCC: Do not edit this line. ScrapitConstants.java */


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScrapitConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int FROM = 7;
  /** RegularExpression Id. */
  int SAVE = 8;
  /** RegularExpression Id. */
  int PRINT = 9;
  /** RegularExpression Id. */
  int LOAD = 10;
  /** RegularExpression Id. */
  int MAP = 11;
  /** RegularExpression Id. */
  int LIKE = 12;
  /** RegularExpression Id. */
  int REGEX = 13;
  /** RegularExpression Id. */
  int STRING_LITERAL = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int EQUAL = 16;
  /** RegularExpression Id. */
  int NOT_EQUAL = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"select\"",
    "\"from\"",
    "\"save\"",
    "\"print\"",
    "\"load\"",
    "\"MAP\"",
    "\"like\"",
    "\"regex\"",
    "<STRING_LITERAL>",
    "\";\"",
    "\"==\"",
    "\"!=\"",
    "\",\"",
  };

}
